server:
  port: 8093
---
spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: Transaccion-created
    processor-out-0:
      destination: Transaccion-updated
---
service:
  endpoints:
    monederoaccount: http://localhost:8092